# Generated by Django 3.0.5 on 2020-07-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opensecrets_id', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=16)),
                ('candidate', models.CharField(max_length=16)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=16)),
                ('issue', models.CharField(max_length=16)),
                ('channel', models.CharField(default='No Type', max_length=16)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=16)),
                ('stance', models.FloatField(default=0.0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chromiumextension.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opensecrets_id', models.CharField(max_length=16)),
                ('name', models.CharField(default='', max_length=128)),
                ('parent_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chromiumextension.Company')),
            ],
        ),
    ]
