# Generated by Django 3.0.5 on 2020-07-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='candidate',
            field=models.CharField(max_length=26),
        ),
    ]
