# Generated by Django 3.0.5 on 2020-06-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0002_auto_20200614_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impact',
            old_name='blm',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='impact',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='impact',
            name='healthcare',
        ),
    ]
