# Generated by Django 3.0.5 on 2020-07-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0002_auto_20200712_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='candidate',
            field=models.CharField(max_length=16),
        ),
    ]
