# Generated by Django 3.0.5 on 2020-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0003_auto_20200616_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='channel',
            field=models.CharField(default='No Type', max_length=16),
        ),
        migrations.AlterField(
            model_name='impact',
            name='issue',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='impact',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stance',
            name='issue',
            field=models.CharField(max_length=16),
        ),
    ]
