# Generated by Django 3.0.5 on 2020-06-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0004_auto_20200617_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='stance',
            field=models.FloatField(default=0.0),
        ),
    ]
