# Generated by Django 3.0.5 on 2020-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0005_auto_20200617_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opensecrets_id',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
