# Generated by Django 3.0.5 on 2020-07-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chromiumextension', '0006_auto_20200706_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chromiumextension.Company'),
        ),
    ]
